service: bash-fake-commit-lambda

provider:
  name: aws
  region: eu-west-1
  ecr:
    images:
      fake_commit_image:
        path: ./

functions:
  fakeCommit:
    image:
      name: fake_commit_image
      command:
        - bootstrap
    environment:
      # IMPORTANT: Update these values before deployment
      GIT_COMMITTER_NAME: "Fake Committer"
      GIT_COMMITTER_EMAIL: "user@domain.com"            # Change this to your email
      REPO_URL: "git@github.com:user/fake-commits.git"  # Change this to your repo URL
    timeout: 30
    events:
      # Run every weekday at 5:15pm UTC
      - schedule: cron(17 15 ? * MON-FRI *)

